version: 2
updates:
  - package-ecosystem: "gradle"
    directories:
      - "/modules/app"
      - "/modules/lib"
      - "/modules/rest"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    assignees:
      - "rymsha"
    reviewers:
      - "rymsha"
  - package-ecosystem: "npm"
    directories:
      - "/modules/app"
      - "/modules/lib"
      - "/testing"
    ignore:
      - dependency-name: "@enonic/lib-admin-ui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "alansemenov"
    reviewers:
      - "alansemenov"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    assignees:
      - "rymsha"
    reviewers:
      - "rymsha"
